---
- name: set_fact ceph_keys - lookup keys in /etc/ceph
  set_fact:
    ceph_keys: "{{ lookup('fileglob', '/etc/ceph/*.keyring') }}"

- name: "copy ceph user and bootstrap keys to the ansible server in {{ fetch_directory }}/{{ fsid }}/"
  fetch:
    src: "{{ item }}"
    dest: "{{ fetch_directory }}/{{ fsid }}/{{ item }}"
    flat: yes
    fail_on_missing: false
  run_once: true
  with_items:
    - "{{ ceph_keys.split(',') }}"
    - "/var/lib/ceph/bootstrap-osd/{{ cluster }}.keyring"
    - "/var/lib/ceph/bootstrap-rgw/{{ cluster }}.keyring"
    - "/var/lib/ceph/bootstrap-mds/{{ cluster }}.keyring"
    - "/var/lib/ceph/bootstrap-rbd/{{ cluster }}.keyring"
    - "/var/lib/ceph/bootstrap-mgr/{{ cluster }}.keyring"